// ========================================================================
//  Audio.js – موديول الصوت، صوت التصادم المعدني مدمج كـ base64
// ========================================================================

const audioCtx = new (window.AudioContext || window.webkitAudioContext)();
let audioBuffer = null;

const BASE64_MP3 = 'SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjYwLjE2LjEwMAAAAAAAAAAAAAAA//tAwAAAAAAAAAAAAAAAAAAAAAAAWGluZwAAAA8AAAAVAAAM6gBOTk5OYmJiYmJvb29vb3d3d3d3f39/f4eHh4eHj4+Pj4+Xl5eXl5+fn5+np6enp6+vr6+vt7e3t7e/v7+/x8fHx8fPz8/Pz9fX19fX39/f3+fn5+fn7+/v7+/39/f39/////8AAAAATGF2YzYwLjMxAAAAAAAAAAAAAAAAJAYeAAAAAAAADOod/jAdAAAAAAD/+9DEAAAI0AF39AAABSBEbL81sJi2UyIkRVwiNUbWXB8Tg4CAIACCFQIAmflwfORAGE/5cHwuD7/SD4Pg+D4IBjxOH4Ph8Tn0I6f//KA+/KOwQB8HwfB8HAQBClpjg0ZSSCIgDSgAAEAAAALmTBIQIDCoEzLgyUOBEGTDA4WZwa7S5S7peFHZMpTZhRdZCamC/ywoGGlqhYhcR0HGgx9oW4LxBcMCAGP0BgZkPVkMoYmEiIfooLFolAWlNCTlL+iEIS1IhVg5h4E2dnJe6aq4qYX5K+L/NyMxIRgGca1SJbm/LgXI5NO4WpqrIdzzKn/hh/Zy/HcaXU1D1PKptHqSv7UhmKw0/wwAgaNWTBkLcq2w1sYUIjBjdnDfWYZpL925E7eqO/WhmtLm7KmaLyNQErawXCmfX7tSrV+JQ9AWNyVVt0sZiV+r/9jNWvp/aaYXdKX5sVnZlr6wLROTDr/TN6IymdqYSqVfLbFieuRmtul3BV63KZqeu//////////6rODOxp61Ss+ZtDUahlwf/////////5bS3ojnhEvoWs1qamXd3u3966gPDE1q4LIpBYEiaHVCrEqv1GRFjIvF420UUdaNFEmSKlUGqcAJyHKkFIsRYiyX/RRRZJR0WaIKoCkgEggBl4NjIoIXMQY2f//+tFlosUhlg9IDAqAGgwlIc0ugJ/fLHYlO+Cr+QcJXQVBXBng1/LA1iU7hgIHx/+tvf//UmgmgXxzBBMDZcwMwHFAEHFzjMDSMW+unoOgdIYLPEBCbHIDAYA4ENlHGGISIG7P/7zt6eWKc7A4DB4bfRxtqAAAAUHaKPwAAK95PqMA+EQqSJDg7gcGWnIePobpEUr6mshWy1LMCmozIYA0xFmJp2////1qJUCEhoKSzJ///+kAQBMMAUEIAfv+1X7//+swA7CdLs6Kqnr//1GYTk1rb/9wmpKhB////TUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVEAcQAfh/W00G4iJ290f//spAA0TU0e3///6ERf/+j/p/////oUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//tgxM+CTwTdQ/yaACEhHCU1QGPEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//swxOcACAjfKeAGS2ClmuP00DfAVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVV//sQxOiDxJjXEsCBTQAAAD/AAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVX/+xDE1gPAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVf/7EMTWA8AAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVV//sQxNYDwAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVX/+xDE1gPAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVf/7EMTWA8AAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVV//sQxNYDwAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVX/+xDE1gPAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVf/7EMTWA8AAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVV//sQxNYDwAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVX/+xDE1gPAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVTEFNRTMuMTAwVVVVVf/7EMTWA8AAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVMQU1FMy4xMDBVVVVV//sQxNYDwAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xDE1gPAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EMTWA8AAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQxNYDwAABpAAAACAAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xDE1gPAAAGkAAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7EMTWA8AAAaQAAAAgAAA0gAAABFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV';

function base64ToArrayBuffer(base64) {
    const binary = atob(base64);
    const bytes  = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    return bytes.buffer;
}

async function init() {
    if (audioBuffer) return;
    try {
        const arrayBuffer = base64ToArrayBuffer(BASE64_MP3);
        audioBuffer = await audioCtx.decodeAudioData(arrayBuffer);
        console.log('✅ Audio.js: تم تحميل صوت التصادم بنجاح');
    } catch (e) {
        console.warn('⚠️ Audio.js: فشل تحميل الصوت', e);
    }
}

function play(velocity) {
    if (!audioBuffer) { init(); return; }
    if (audioCtx.state === 'suspended') audioCtx.resume();

    const intensity = Math.min(1.0, Math.abs(velocity) / 3.0);
    if (intensity < 0.05) return; // تجاهل التصادمات الخفيفة جداً

    const source   = audioCtx.createBufferSource();
    source.buffer  = audioBuffer;

    const gainNode = audioCtx.createGain();
    gainNode.gain.value = 0.3 + intensity * 0.7; // الحجم يتناسب مع شدة التصادم

    source.connect(gainNode);
    gainNode.connect(audioCtx.destination);
    source.start();
}

// تفعيل الـ AudioContext عند أول تفاعل للمستخدم (متطلب المتصفحات)
document.addEventListener('mousedown', () => { audioCtx.resume(); init(); }, { once: true });
document.addEventListener('keydown',   () => { audioCtx.resume(); init(); }, { once: true });
document.addEventListener('touchstart', () => { audioCtx.resume(); init(); }, { once: true });

// تصدير كـ ES Module للاستخدام في NewtonCradle.js
export const CradleAudio = { play };
